export const GAME_ACTIVE = 2
export const GAME_COMPLETED = 3

export const LOADING_STATUS_PROVIDER_NOT_LOADED = 1;
export const LOADING_STATUS_PROVIDER_LOADED = 2;
export const LOADING_STATUS_NO_PERMISSIONS = 3;
export const LOADING_STATUS_GAME_PENDING = 4;
export const LOADING_STATUS_EMPTY_GAME_LIST = 5;

export const CLAIM_COST_MAX = 8000000000;
export const MIN_MSG_VALUE = 200000000;
